# Generated by Django 5.1.3 on 2025-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.CharField(max_length=190),
        ),
    ]
