# Generated by Django 5.1.3 on 2025-04-16 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Enter a valid phone number.')]),
        ),
    ]
