# Generated by Django 5.2 on 2025-05-30 23:09

import django.db.models.deletion
import screening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_applicant_birthdate_alter_applicant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('latitude', models.FloatField(validators=[screening.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[screening.models.validate_longitude])),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy')], default='healthy', max_length=20)),
                ('api_key', models.CharField(max_length=40, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.FloatField()),
                ('latitude', models.FloatField(validators=[screening.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[screening.models.validate_longitude])),
                ('status_code', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('edge_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='screening.edgenode')),
            ],
        ),
    ]
