# Generated by Django 5.2 on 2025-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_edgenode_apirequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgenode',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
